import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { motion } from "framer-motion";

export default function Home() {
  const menu = () => {
    document.querySelector("#drop-down").style.display = "block";
  }
  const close = () => {
    document.querySelector("#drop-down").style.display = "none";
  }
  return (
    <>
      <Head>
        <title>Adult-Edu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
        <link rel="icon" href="/Logo.svg" />
      </Head>
      
      <div id={styles.container}>
        <motion.div id="drop-down"
          initial={{y:-100}}
          whileInView={{y:0}}
          transition={{duration:1}}
        >
          <i class="fa-solid fa-xmark" onClick={close}></i>
          <nav>
            <Link href="/Signup">Home</Link>
            <Link href="/Signup">Literacy</Link>
            <Link href="/Signup">Adulthood Concept</Link>
            <Link href="/Signup">Life Long Leanring </Link>
          </nav>
        </motion.div>
        <motion.header
          initial={{y:-100}}
          whileInView={{y:0}}
          transition={{duration:1.2}}
        >
          <img src="/Logo.svg" />
          <nav>
            <Link href="/Signup">Home</Link>
            <Link href="/Signup">Literacy</Link>
            <Link href="/Signup">Adulthood Concept</Link>
            <Link href="/Signup">Life Long Leanring </Link>
          </nav>
          <Link href="/Signup">Adult-Edu</Link>
          <i className="fa-solid fa-bars" id={styles.menu} onClick={menu}></i>
        </motion.header>

        <section>
          <motion.div
            initial={{y:100}}
            whileInView={{y:0}}
            transition={{duration:1.3}}
          >
            <h1>Unlock Your Potential with Lifelong Learning</h1>
            <p>At Adult Edu, we empower adult learners with practical, job-ready skills through flexible and effective learning programs.</p>
            <p>Whether you're looking to enhance your expertise, switch careers, or develop new opportunities, our courses are designed to help you achieve your goals—quickly and efficiently.</p>
            <button onClick={() => {
              document.querySelector("#sig").click();
            }}>Enroll Now</button>
          </motion.div>
          <motion.img src="/hero-sec.svg" 
            initial={{x:100}}
            whileInView={{x:0}}
            transition={{duration:1.3}}
          />
        </section>

        <main>
          <section>
            <motion.div
              initial={{y:100}}
              whileInView={{y:0}}
              transition={{duration:1.3}}
            >
              <h2>About Adult-Edu</h2>
              <p>The Adult Education and Family Literacy Act (Adult-Edu) is dedicated to empowering individuals through lifelong learning. Our programs support adult learners, including those with little to no prior education, by equipping them with essential literacy, communication, and problem-solving skills. AEFLA aims to foster self-sufficiency and professional growth, ensuring every learner has the tools to succeed in today’s evolving world.</p>
              <button onClick={() => {
                document.querySelector("#sig").click();
              }}>Continue Reading</button>
            </motion.div>
            <motion.img src="/pic2.svg" 
              initial={{x:100}}
              whileInView={{x:0}}
              transition={{duration:1.3}}
            />
          </section>

          <article>
            <motion.h2
              initial={{y:100}}
              whileInView={{y:0}}
              transition={{duration:1}}
            >Why Adult Education and Family Literacy Act (AEFLA) </motion.h2>
            <motion.p
              initial={{y:100}}
              whileInView={{y:0}}
              transition={{duration:1}}
            >The Adult Education and Family Literacy Act (AEFLA) is dedicated to empowering individuals through lifelong learning. Our programs support adult learners, including those with little to no prior education, by equipping them with essential literacy, communication, and problem-solving skills. AEFLA aims to foster self-sufficiency and professional growth, ensuring every learner has the tools to succeed in today’s evolving world.</motion.p>
            <motion.button
              initial={{x:100, opacity:0}}
              whileInView={{x:0, opacity:1}}
              transition={{duration:1, delay:0.3}}
              onClick={() => {
                document.querySelector("#sig").click();
              }}
            >Continue Reading</motion.button>
          </article>
        </main>

        <summary>
          <h2>(AEFLA) Stands Out </h2>
          <article>
            <div>
              <img src="/edu.svg" />
              <h4>Constant Practicing on  Adult Learners</h4>
              <p>AEFLA Provides 90% support for learners to learn and relearn and unlearn to have full knowledge of what they lost when they are not in the school settings. </p>
            </div>
            <div>
              <img src="/icon2.svg" />
              <h4>Relevant of Learning After out of School </h4>
              <p>AEFLA Provides 90% support for learners to learn and relearn and unlearn to have full knowledge of what they lost when they are not in the school settings. </p>
            </div>
          </article>
          <article>
            <div>
              <img src="/icon3.svg" />
              <h4>Non Formal & Informal Education Knowledge </h4>
              <p>AEFLA Provides 90% support for learners to learn and relearn and unlearn to have full knowledge of what they lost when they are not in the school settings. </p>
            </div>
            <div>
              <img src="/carbon_license-global.svg" />
              <h4>Adequate Staffs Globally </h4>
              <p>AEFLA Provides 90% support for learners to learn and relearn and unlearn to have full knowledge of what they lost when they are not in the school settings. </p>
            </div>
          </article>

          <section>
            <h2>What Our Clients & Learner Says.</h2>
            <aside>
              <nav>
                <img src="/icon5.svg" />
                <h4>Abdulmalik</h4>
                <p>Adult Education Classes from AEFLA gave me the chance to learn and be able to communicate with my fellow colleagues in the office</p>
              </nav>
              <nav>
                <img src="/icon5.svg" />
                <h4>Imran Musa</h4>
                <p>Adult Education Classes from AEFLA gave me the chance to learn and be able to communicate with my fellow colleagues in the office</p>
              </nav>
              <nav>
                <img src="/icon5.svg" />
                <h4>codeWithFaith</h4>
                <p>Adult Education Classes from AEFLA gave me the chance to learn and be able to communicate with my fellow colleagues in the office</p>
              </nav>
            </aside>
          </section>
        </summary>

        <aside>
          <motion.h1
            initial={{y:100}}
            whileInView={{y:0}}
            transition={{duration:1}}
          >Where Our Learners use to acquire Knowledge and Lessons </motion.h1>
          <article>
            <motion.div
              initial={{y:100}}
              whileInView={{y:0}}
              transition={{duration:1}}
            >
              <p>Our Learning environment gives you the comfortability to study effectively and the inspiration to stay focused.</p>
              <p>You will have access to adequate power supply in our cool and pristine learning hub</p>
              <p>Register for one of our programs to learn at the top learning facility in Ibadan.</p>
            </motion.div>
            <motion.img src="/Frame.png" 
              initial={{x:100}}
              whileInView={{x:0}}
              transition={{duration:1}}
            />
          </article>
        </aside>

        <footer>
          <nav>
            <h2>Get In Touch With Us Sharp </h2>
            <p>Join our classes now and start solving your own problems on your own despite that you are out of school system or shy. </p>
          </nav>
          <div>
            <nav>
              <h2>Locate Us</h2>
              <p>Address: No 18/B, Inside Barika, The Great Tutorial,Opposite University of Ibadan Second gate, </p>
              <p>Phone: 09076956531, +2349058704410.</p>
            </nav>
            <img src="/map.svg" />
          </div>

          <section>
            <img src="/Logo.svg" />
            <nav>
              <h4>About</h4>
              <Link href="#">Home</Link>
              <Link href="#">Features</Link>
              <Link href="#">FAQS</Link>
              <Link href="#">Reviews</Link>
              <Link href="#">Stories</Link>
            </nav>
            <nav>
              <h4>Privacy</h4>
              <Link href="#">Privacy</Link>
              <Link href="#">Policy</Link>
              <Link href="#">Payment</Link>
              <Link href="#">Terms</Link>
            </nav>
            <nav>
              <h4>Shop</h4>
              <Link href="#">All collections</Link>
              <Link href="#">Winter Edition</Link>
              <Link href="#">Discount</Link>
            </nav>
          </section>

          <summary>
            <img src="X.svg" />
            <img src="LinkedIn.svg" />
            <img src="Instagram.svg" />
            <img src="YouTube.svg" />
          </summary>
        </footer>
        <Link href="/Signup" id="sig"></Link>
      </div>
    </>
  );
}
