import Head from "next/head";
import Link from "next/link";
import { motion } from "framer-motion";
import Styles from "../styles/Literacy.module.css";

const Literacy = () => {
    const menu = () => {
        document.querySelector("#drop-down").style.display = "block";
    }
    const close = () => {
        document.querySelector("#drop-down").style.display = "none";
    }
    return(
        <>
            <Head>
                <title>Adult-Edu | Enroll</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
                <link rel="icon" href="/Logo.svg" />
            </Head>
            <div id={Styles.literacy}>
                <motion.div id="drop-down"
                    initial={{y:-100}}
                    whileInView={{y:0}}
                    transition={{duration:1}}
                    >
                    <i class="fa-solid fa-xmark" onClick={close}></i>
                    <nav>
                        <Link href="/Dashboard">Home</Link>
                        <Link href="/literacy">Literacy</Link>
                        <Link href="#">Adulthood Concept</Link>
                        <Link href="#">Life Long Leanring </Link>
                    </nav>
                </motion.div>
                <motion.header
                    initial={{y:-60}}
                    whileInView={{y:0}}
                    transition={{duration:1.2}}
                    >
                    <img src="/Logo.svg" />
                    <nav>
                        <Link href="/Dashboard">Home</Link>
                        <Link href="/LiteracyPage">Literacy</Link>
                        <Link href="/Adulthood">Adulthood Concept</Link>
                        <Link href="/Livelong">Life Long Leanring </Link>
                    </nav>
                    <i className="fa-solid fa-bars" id={Styles.menu} onClick={menu}></i>
                    <img src="/profile.png" />
                </motion.header>

                <section>
                    <nav>
                        <h1>Full Package Adult Class Online.</h1>
                        <p>We offer the best prices for the value we give our Learners.</p>
                    </nav>
                    <motion.img src="/pic2.svg" 
                        initial={{x:100}}
                        whileInView={{x:0}}
                        transition={{duration:1.3}}
                    />
                </section>

                <article>
                    <nav>
                        <h4>LITERACY CLASS</h4>
                        <p>Free Open Source</p>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <button onClick={() => {
                            document.querySelector("#page").click();
                        }}>Continue Learning</button>
                    </nav>
                    <nav className="nav">
                        <h4>LITERACY CLASS</h4>
                        <p>Free Open Source</p>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <button onClick={() => {
                            document.querySelector("#page").click();
                        }}>Continue Learning</button>
                    </nav>
                    <nav>
                        <h4>LITERACY CLASS</h4>
                        <p>Free Open Source</p>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <li>Utilizing Digital For Learning As an Adult Person.</li>
                        <button onClick={() => {
                            document.querySelector("#page").click();
                        }}>Continue Learning</button>
                    </nav>
                </article>

                <summary>
                    <h2>(AEFLA) Stands Out </h2>
                    <article>
                        <div>
                        <img src="/edu.svg" />
                        <h4>Constant Practicing on  Adult Learners</h4>
                        <p>AEFLA Provides 90% support for learners to learn and relearn and unlearn to have full knowledge of what they lost when they are not in the school settings. </p>
                        </div>
                        <div>
                        <img src="/icon2.svg" />
                        <h4>Relevant of Learning After out of School </h4>
                        <p>AEFLA Provides 90% support for learners to learn and relearn and unlearn to have full knowledge of what they lost when they are not in the school settings. </p>
                        </div>
                    </article>
                    <article>
                        <div>
                        <img src="/icon3.svg" />
                        <h4>Non Formal & Informal Education Knowledge </h4>
                        <p>AEFLA Provides 90% support for learners to learn and relearn and unlearn to have full knowledge of what they lost when they are not in the school settings. </p>
                        </div>
                        <div>
                        <img src="/carbon_license-global.svg" />
                        <h4>Adequate Staffs Globally </h4>
                        <p>AEFLA Provides 90% support for learners to learn and relearn and unlearn to have full knowledge of what they lost when they are not in the school settings. </p>
                        </div>
                    </article>

                    <section>
                        <h2>What Our Clients & Learner Says.</h2>
                        <aside>
                        <nav>
                            <img src="/icon5.svg" />
                            <h4>Abdulmalik</h4>
                            <p>Adult Education Classes from AEFLA gave me the chance to learn and be able to communicate with my fellow colleagues in the office</p>
                        </nav>
                        <nav>
                            <img src="/icon5.svg" />
                            <h4>Imran Musa</h4>
                            <p>Adult Education Classes from AEFLA gave me the chance to learn and be able to communicate with my fellow colleagues in the office</p>
                        </nav>
                        <nav>
                            <img src="/icon5.svg" />
                            <h4>codeWithFaith</h4>
                            <p>Adult Education Classes from AEFLA gave me the chance to learn and be able to communicate with my fellow colleagues in the office</p>
                        </nav>
                        </aside>
                    </section>
                </summary>


                <aside>
                    <motion.h1
                        initial={{y:100}}
                        whileInView={{y:0}}
                        transition={{duration:1}}
                    >Where Our Learners use to acquire Knowledge and Lessons </motion.h1>
                    <article>
                        <motion.div
                        initial={{y:100}}
                        whileInView={{y:0}}
                        transition={{duration:1}}
                        >
                        <p>Our Learning environment gives you the comfortability to study effectively and the inspiration to stay focused.</p>
                        <p>You will have access to adequate power supply in our cool and pristine learning hub</p>
                        <p>Register for one of our programs to learn at the top learning facility in Ibadan.</p>
                        </motion.div>
                        <motion.img src="/Frame.png" 
                        initial={{x:100}}
                        whileInView={{x:0}}
                        transition={{duration:1}}
                        />
                    </article>
                    </aside>

                    <footer>
                    <nav>
                        <h2>Get In Touch With Us Sharp </h2>
                        <p>Join our classes now and start solving your own problems on your own despite that you are out of school system or shy. </p>
                    </nav>
                    <div>
                        <nav>
                        <h2>Locate Us</h2>
                        <p>Address: No 18/B, Inside Barika, The Great Tutorial,Opposite University of Ibadan Second gate, </p>
                        <p>Phone: 09076956531, +2349058704410.</p>
                        </nav>
                        <img src="/map.svg" />
                    </div>

                    <section>
                        <img src="/Logo.svg" />
                        <nav>
                        <h4>About</h4>
                        <Link href="#">Home</Link>
                        <Link href="#">Features</Link>
                        <Link href="#">FAQS</Link>
                        <Link href="#">Reviews</Link>
                        <Link href="#">Stories</Link>
                        </nav>
                        <nav>
                        <h4>Privacy</h4>
                        <Link href="#">Privacy</Link>
                        <Link href="#">Policy</Link>
                        <Link href="#">Payment</Link>
                        <Link href="#">Terms</Link>
                        </nav>
                        <nav>
                        <h4>Shop</h4>
                        <Link href="#">All collections</Link>
                        <Link href="#">Winter Edition</Link>
                        <Link href="#">Discount</Link>
                        </nav>
                    </section>

                    <summary>
                        <img src="X.svg" />
                        <img src="LinkedIn.svg" />
                        <img src="Instagram.svg" />
                        <img src="YouTube.svg" />
                    </summary>
                </footer>
                <Link href="/LiteracyPage" id="page"></Link>
            </div>
        </>
    )
}
export default Literacy;