import Head from "next/head"
import Link from "next/link";
import { motion } from "framer-motion";
import Styles from "../styles/LiteracyPage.module.css";

export default function LiteracyPage() {
    const menu = () => {
        document.querySelector("#drop-down").style.display = "block";
    }
    const close = () => {
        document.querySelector("#drop-down").style.display = "none";
    }
    return(
        <>
            <Head>
                <title>Adult-Edu | Literacy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
                <link rel="icon" href="/Logo.svg" />
            </Head>

            <div id={Styles.LiteracyPage}>
                <motion.div id="drop-down"
                    initial={{y:-100}}
                    whileInView={{y:0}}
                    transition={{duration:1}}
                    >
                    <i class="fa-solid fa-xmark" onClick={close}></i>
                    <nav>
                        <Link href="/Dashboard">Home</Link>
                        <Link href="/LiteracyPage">Literacy</Link>
                        <Link href="/Adulthood">Adulthood Concept</Link>
                        <Link href="/Livelong">Life Long Leanring </Link>
                    </nav>
                </motion.div>
                <motion.header
                    initial={{y:-70}}
                    whileInView={{y:0}}
                    transition={{duration:1.2}}
                    >
                    <img src="/Logo.svg" />
                    <nav>
                        <Link href="/Dashboard">Home</Link>
                        <Link href="/LiteracyPage">Literacy</Link>
                        <Link href="/Adulthood">Adulthood Concept</Link>
                        <Link href="/Livelong">Life Long Leanring </Link>
                    </nav>
                    <i className="fa-solid fa-bars" id={Styles.menu} onClick={menu}></i>
                    <img src="/profile.png" />
                </motion.header>

                <section>
                    <img src="/image 772.png" alt="" />
                    <nav>
                        <h4>What Adult Needs to Know </h4>
                        <li> 📖 Basic Literacy Skills</li>
                        <li>💬 Communication and Language Skills</li>
                        <li> 💻 Digital Literacy</li>
                        <li>🧾 Financial and Economic Literacy</li>
                        <li>🌍 Civic and Political Awareness</li>
                    </nav>
                </section>

                <article>
                    <h1>Literacy goes beyond reading and writing.</h1>
                    <section>
                        <div>
                            <img src="/Frame163.png" alt="" />
                            <p>— reading everyday texts like forms, bills, or signs.</p>
                        </div>
                        <div>
                            <img src="/image 771.png" alt="" />
                            <p> using phones, computers, and online tools.</p>
                        </div>
                        <div>
                            <img src="/Frame162.png" alt="" />
                            <p>understanding numbers, money, and measurements.</p>
                        </div>
                        <div>
                            <img src="/Frame161.png" />
                            <p>understanding rights, responsibilities, and participation in society.</p>
                        </div>
                    </section>
                </article>

                <summary>
                    <h1>Literacy Learning</h1>
                    <nav>
                        <div>
                            <img src="/pro.png" alt="" />
                            <h4>Reading & Pronunciation Practice</h4>
                            <button>Start Learning</button>
                        </div>
                        <div>
                            <img src="/pro.png" alt="" />
                            <h4>Reading & Pronunciation Practice</h4>
                            <button>Start Learning</button>
                        </div>
                        <div>
                            <img src="/pro.png" alt="" />
                            <h4>Reading & Pronunciation Practice</h4>
                            <button>Start Learning</button>
                        </div>
                    </nav>
                </summary>

                <footer>
                    <nav>
                        <h2>Get In Touch With Us Sharp </h2>
                        <p>Join our classes now and start solving your own problems on your own despite that you are out of school system or shy. </p>
                    </nav>
                    <div>
                        <nav>
                        <h2>Locate Us</h2>
                        <p>Address: No 18/B, Inside Barika, The Great Tutorial,Opposite University of Ibadan Second gate, </p>
                        <p>Phone: 09076956531, +2349058704410.</p>
                        </nav>
                        <img src="/map.svg" />
                    </div>

                    <section>
                        <img src="/Logo.svg" />
                        <nav>
                        <h4>About</h4>
                        <Link href="#">Home</Link>
                        <Link href="#">Features</Link>
                        <Link href="#">FAQS</Link>
                        <Link href="#">Reviews</Link>
                        <Link href="#">Stories</Link>
                        </nav>
                        <nav>
                        <h4>Privacy</h4>
                        <Link href="#">Privacy</Link>
                        <Link href="#">Policy</Link>
                        <Link href="#">Payment</Link>
                        <Link href="#">Terms</Link>
                        </nav>
                        <nav>
                        <h4>Shop</h4>
                        <Link href="#">All collections</Link>
                        <Link href="#">Winter Edition</Link>
                        <Link href="#">Discount</Link>
                        </nav>
                    </section>

                    <summary>
                        <img src="X.svg" />
                        <img src="LinkedIn.svg" />
                        <img src="Instagram.svg" />
                        <img src="YouTube.svg" />
                    </summary>
                </footer>
            </div>
        </>
    )
}