import Head from "next/head";
import Link from "next/link";
import { motion } from "framer-motion";
import Styles from "../styles/Adulthood.module.css";

export default function AdultHood(){
    const menu = () => {
        document.querySelector("#drop-down").style.display = "block";
    }
    const close = () => {
        document.querySelector("#drop-down").style.display = "none";
    }
    return(
        <>
            <Head>
                <title>Adult-Edu | Live Long Learning</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
                <link rel="icon" href="/Logo.svg" />
            </Head>

            <div id={Styles.AdultHood}>
                <motion.div id="drop-down"
                    initial={{y:-100}}
                    whileInView={{y:0}}
                    transition={{duration:1}}
                    >
                    <i class="fa-solid fa-xmark" onClick={close}></i>
                    <nav>
                        <Link href="/Dashboard">Home</Link>
                        <Link href="/LiteracyPage">Literacy</Link>
                        <Link href="/Adulthood">Adulthood Concept</Link>
                        <Link href="/Livelong">Life Long Leanring </Link>
                    </nav>
                </motion.div>

                <motion.header
                    initial={{y:-50}}
                    whileInView={{y:0}}
                    transition={{duration:1.2}}
                    >
                    <img src="/Logo.svg" />
                    <nav>
                        <Link href="/Dashboard">Home</Link>
                        <Link href="/LiteracyPage">Literacy</Link>
                        <Link href="/Adulthood">Adulthood Concept</Link>
                        <Link href="/Livelong">Life Long Leanring </Link>
                    </nav>
                    <i className="fa-solid fa-bars" id={Styles.menu} onClick={menu}></i>
                    <img src="/profile.png" />
                </motion.header>

                <section>
                    <nav>
                        <h4>Life Long Learning Growing Beyond the Classroom</h4>
                        <li>Formal Learning</li>
                        <li>Non-Formal Learning</li>
                        <li>Informal Learning</li>
                    </nav>
                    <img src="/image 772.png" alt="" />
                </section>
                <img src="/adult.png" />

                <h1>AdultHood Concept</h1>

                <article>
                    <div>
                        <img src="/adult.png" alt="adult" />
                        <h4>Independence and Responsibility:</h4>
                        <p>Adults are expected to make their own choices, manage finances, handle relationships, and take responsibility for both successes and mistakes.</p>
                    </div>
                    <div>
                        <img src="/dollar.png" alt="adult" />
                        <h4>Independence and Responsibility:</h4>
                        <p>Establishing a career, earning income, and managing resources are central aspects of adulthood.</p>
                    </div>
                </article>
                <article>
                    <div>
                        <img src="/emotion.png" alt="adult" />
                        <h4>Emotional Maturity:</h4>
                        <p>Adulthood requires the ability to manage emotions, resolve conflicts, and make balanced decisions rather than reacting impulsively.</p>
                    </div>
                    <div>
                        <img src="/image 771 (1).png" alt="adult" />
                        <h4>Social Roles :</h4>
                        <p>Adults often play multiple roles — as workers, parents, citizens, or community members — and must balance these roles effectively.</p>
                    </div>
                </article>

                <footer>
                    <nav>
                        <h2>Get In Touch With Us Sharp </h2>
                        <p>Join our classes now and start solving your own problems on your own despite that you are out of school system or shy. </p>
                    </nav>
                    <div>
                        <nav>
                        <h2>Locate Us</h2>
                        <p>Address: No 18/B, Inside Barika, The Great Tutorial,Opposite University of Ibadan Second gate, </p>
                        <p>Phone: 09076956531, +2349058704410.</p>
                        </nav>
                        <img src="/map.svg" />
                    </div>

                    <section>
                        <img src="/Logo.svg" />
                        <nav>
                        <h4>About</h4>
                        <Link href="#">Home</Link>
                        <Link href="#">Features</Link>
                        <Link href="#">FAQS</Link>
                        <Link href="#">Reviews</Link>
                        <Link href="#">Stories</Link>
                        </nav>
                        <nav>
                        <h4>Privacy</h4>
                        <Link href="#">Privacy</Link>
                        <Link href="#">Policy</Link>
                        <Link href="#">Payment</Link>
                        <Link href="#">Terms</Link>
                        </nav>
                        <nav>
                        <h4>Shop</h4>
                        <Link href="#">All collections</Link>
                        <Link href="#">Winter Edition</Link>
                        <Link href="#">Discount</Link>
                        </nav>
                    </section>

                    <summary>
                        <img src="X.svg" />
                        <img src="LinkedIn.svg" />
                        <img src="Instagram.svg" />
                        <img src="YouTube.svg" />
                    </summary>
                </footer>
            </div>
        </>
    )
}