import Head from "next/head";
import Link from "next/link";
import Styles from "../styles/Sign.module.css";
import { signInWithEmailAndPassword, signInWithPopup } from "firebase/auth";
import { auth, googleProvider } from "../lib/firebase";

export default function Login() {
  async function login() {
    const email = document.getElementById("loginUsername").value;
    const password = document.getElementById("loginPassword").value;

    if (!email || !password) {
      alert("Please fill in both fields.");
      return;
    }

    try {
      const userCredential = await signInWithEmailAndPassword(auth, email, password);
      const user = userCredential.user;

      if (!user.emailVerified) {
        alert("Please verify your email before logging in. Check your inbox!");
        return;
      }

      document.getElementById("log").click();
    } catch (error) {
      console.error(error);
      if (error.code === "auth/invalid-credential") {
        alert("Invalid email or password.");
      } else {
        alert(error.message);
      }
    }
  }

  async function loginWithGoogle() {
    try {
      const result = await signInWithPopup(auth, googleProvider);
      const user = result.user;
      alert(`Welcome ${user.displayName || "User"}!`);
      document.getElementById("log").click();
    } catch (error) {
      console.error(error);
      alert(error.message);
    }
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <div id={Styles.sign}>
        <section>
          <nav>
            <img src="/Logo.svg" />
            <h2>Explore The Process Of Adult Learning.</h2>
            <h2>No Stopping in Learning for knowledge</h2>
          </nav>
          <img src="/image 770.svg" />
        </section>

        <article>
          <p>
            Doesn't Have An Account ? <Link href="/Signup">Sign Up</Link>
          </p>

          <button onClick={loginWithGoogle}>
            <i className="fa-brands fa-google"></i> Login with Google
          </button>

          <aside>
            <legend>Login to Your Account</legend>
            <p>
              Welcome to the page of Adult Users, where to learn and explore for those who are not
              privileged to attend formal school.
            </p>

            <nav>
              <label>Email</label>
              <input type="email" id="loginUsername" required />
            </nav>

            <nav>
              <label>Password</label>
              <input type="password" id="loginPassword" required />
            </nav>

            <nav>
              <button onClick={login}>Login</button>
            </nav>

            <Link href="/Dashboard" id="log"></Link>
          </aside>
        </article>
      </div>
    </>
  );
}
