import Head from "next/head";
import Link from "next/link";
import Styles from "../styles/Sign.module.css"; 

export default function Signup() {
    return(
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
                <link rel="icon" href="/Logo.svg" />
            </Head>

            <div id={Styles.sign}>
                <section>
                    <nav>
                        <img src="/Logo.svg" />
                        <h2>Explore The Process Of Adult Learning. </h2>
                        <h2>No Stopping in Learning for knowledge</h2>
                    </nav>
                    <img src="/image 770.svg" />
                </section>
                <article>
                    <p>Doesn't Have An Account ? <Link href="/Signup">Sign Up</Link></p>
                    <aside>
                        <legend>Login to Your Account</legend>
                        <p>Welcome to the page of Adult Users, where to learn and explore for those who are not privilege to attend formal school.</p>
                        
                        <nav>
                            <label>Username</label>
                            <input type="text" required />
                        </nav>
                        <nav>
                            <label>Password</label>
                            <input type="password" required />
                        </nav>
                        <nav>
                            <button onClick={() => {
                                document.querySelector("#log").click();
                            }}>Login</button>
                        </nav>
                        <Link href="/Dashboard" id="log"></Link>
                    </aside>
                    
                </article>
            </div>
        </>
    )
}