import Head from "next/head";
import Link from "next/link";
import Styles from "../styles/Sign.module.css"; 

export default function Signup() {
    function Create() { 
        const username = document.getElementById("signupUsername").value; 
        const password = document.getElementById("signupPassword").value; 
        
        if (!username || !password) { 
            alert("fill all the fields");
        } 
        let users = JSON.parse(localStorage.getItem("users")) || []; 
        if (username && password) { 
            document.querySelector("#log").click();
            users.push({ username, password }); 
            localStorage.setItem("users", JSON.stringify(users));
        }else if(users.find(user => user.username === username && user.password === password)){
            alert("Email already exists.");
        }
    }
    return(
        <>
            <Head>
                <title>Sign up</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
                <link rel="icon" href="/Logo.svg" />
            </Head>

            <div id={Styles.sign}>
                <section>
                    <nav>
                        <img src="/Logo.svg" />
                        <h2>Explore The Process Of Adult Learning. </h2>
                        <h2>No Stopping in Learning for knowledge</h2>
                    </nav>
                    <img src="/image 770.svg" />
                </section>
                <article>
                    <p>Already Have An Account ? <Link href="/Login">Sign In</Link></p>
                    <aside>
                        <legend>Create Account</legend>
                        <nav>
                            <label>Name</label>
                            <input type="text" required />
                        </nav>
                        <nav>
                            <label>Email</label>
                            <input type="email" required />
                        </nav>
                        <nav>
                            <label>Username</label>
                            <input type="text" id="signupUsername" required />
                        </nav>
                        <nav>
                            <label>Password</label>
                            <input type="password" id="signupPassword" required />
                        </nav>
                        <nav>
                            <p><input type="checkbox"/> I agree to follow the privacy information</p>
                        </nav>
                        <nav>
                            <button onClick={Create}>Sign Up</button>
                        </nav>
                        <Link href="/Login" id="log"></Link>
                    </aside>
                </article>

            </div>
        </>
    )
}