import Head from "next/head";
import Link from "next/link";
import Styles from "../styles/Sign.module.css";
import { useState } from "react";
import { auth, googleProvider } from "../lib/firebase";
import {
  createUserWithEmailAndPassword,
  sendEmailVerification,
  signInWithPopup,
} from "firebase/auth";

export default function Signup() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSignup = async () => {
    if (!name || !email || !username || !password) {
      alert("Please fill all fields");
      return;
    }

    try {
      setLoading(true);
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      const user = userCredential.user;
      await sendEmailVerification(user);
      alert("Account created! Please check your email to verify your account.");
    } catch (error) {
      alert(error.message);
    } finally {
      setLoading(false);
    }
  };

  const handleGoogleSignup = async () => {
    try {
      setLoading(true);
      const result = await signInWithPopup(auth, googleProvider);
      const user = result.user;
      alert(`Welcome ${user.displayName || "User"}! Your Google account is connected.`);
    } catch (error) {
      alert(error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <div id={Styles.sign}>
        <section>
          <nav>
            <img src="/Logo.svg" />
            <h2>Explore The Process Of Adult Learning.</h2>
            <h2>No Stopping in Learning for knowledge</h2>
          </nav>
          <img src="/image 770.svg" />
        </section>

        <article>
          <p>
            Already Have An Account ? <Link href="/Login">Sign In</Link>
          </p>

          <button id="google" onClick={handleGoogleSignup} disabled={loading}>
            <i className="fa-brands fa-google"></i> Continue with Google
          </button>

          <aside>
            <legend>Create Account</legend>

            <nav>
              <label>Name</label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
              />
            </nav>

            <nav>
              <label>Email</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </nav>

            <nav>
              <label>Username</label>
              <input
                type="text"
                id="signupUsername"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                required
              />
            </nav>

            <nav>
              <label>Password</label>
              <input
                type="password"
                id="signupPassword"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </nav>

            <nav>
              <p>
                <input type="checkbox" required /> I agree to follow the privacy information
              </p>
            </nav>

            <nav>
              <button onClick={handleSignup} disabled={loading}>
                {loading ? "Creating..." : "Sign Up"}
              </button>
            </nav>

            <Link href="/Login" id="log"></Link>
          </aside>
        </article>
      </div>
    </>
  );
}
